# TEC - The Elidoras Codex Funding Platforms
# This file directs supporters to your funding channels via the GitHub Sponsor button.

# GitHub Sponsors: Add your GitHub username here.
github: Elidorascodex

# Patreon: This is your primary community support platform.
# NOTE: I've used 'elidorascodex' as the username based on your other social links.
# Please verify this is your correct Patreon username.
patreon: elidorascodex

# Custom Link: A direct link to your website's support/join page.
# This gives people a central place to learn more about supporting TEC.
custom: https://elidorascodex.com
